#!/usr/bin/env bash
# The script that kill a processe
# usinf the 'ctr+c' to kill the process
# then print out 'Why u no love me ' and other messages

terminator() {
    rm /var/run/myscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo 'To infinity and beyond'
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
