#!/usr/bin/env bash
# This script kills a process of 'To infinity and beyond'
# using the SIGTERM 'I am invisible !!'

trap "echo 'I am invincible!!!'" SIGTERM
while :; do echo "To infinity and beyond"; sleep 2; done
