#!/usr/bin/env bash
# This script checks the existance and properties of a file
# the file were are checking is 'school'

thefile="School"
if [ -e $thefile ]
then
	echo "school file exists"
	if [ -s $thefile ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $thefile ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
